name: Testing filters in gitgub actions

on: 
  push:
    branches:
      - main
    paths-ignore: 
      - "content/**"
      - "file1.txt"
      
  pull_request:
    branches: ["main"]
    paths-ignore: 
      - "content/**"
      - "file1.txt"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show info
        run: echo "Hello World"