name: Basic info
on: 
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

jobs:

  showinfo:
    runs-on: ubuntu-latest
    steps:
      - name: show message 
        run: echo "Hello everyone!"