name: filter by jobs in PR's
on: 
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

jobs:

  check_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check if message contain keywords as scope
        id: check_commit
        run: |
          message=$(git log -1 --pretty=format:'%s')
          re="\[(doc|skip-tests)\]"
          if [[ $message =~ $re ]]; then
            echo "::set-output name=match::true"
            echo "$message -> Match is true"
          else
            echo "$message -> Match is false"
          fi
    outputs:
      match: ${{ steps.check_commit.outputs.match }}

  testing:
    needs: check_commit
    if: ${{ needs.check_commit.outputs.match != 'true' }}
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: test stuffs 
        run: echo "Simulating tests"
